# Generated by Django 4.2.5 on 2023-09-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_users_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
